apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scd-reporting.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "scd-reporting.selectorLabels" (dict "root" . "component" "caddy") | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "scd-reporting.selectorLabels" (dict "root" . "component" "caddy") | nindent 8 }}
    spec:
      containers:
        - name: caddy
          image: "{{ .Values.caddy.image.repository }}:{{ .Values.caddy.image.tag }}"
          imagePullPolicy: {{ .Values.caddy.image.pullPolicy }}
          env:
            - name: SCD_HOSTNAME
              value: {{ .Values.caddy.hostname | quote }}
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 443
              protocol: UDP
          volumeMounts:
            - mountPath: /etc/caddy/Caddyfile
              name: caddyfile
              readOnly: true
              subPath: Caddyfile
            - mountPath: /srv/static
              name: staticfiles
              readOnly: true
            - mountPath: /srv/media
              name: media
              readOnly: true
            - mountPath: /data
              name: caddy-data
            - mountPath: /config
              name: caddy-config
      restartPolicy: Always
      volumes:
        - name: caddyfile
          configMap:
            name: {{ .Release.Name }}-caddyfile
            items:
              - key: Caddyfile
                path: Caddyfile
        - name: staticfiles
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-staticfiles
            readOnly: true
        - name: media
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-media
            readOnly: true
        - name: caddy-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-caddy-data
        - name: caddy-config
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-caddy-config
