apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scd-reporting.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "scd-reporting.selectorLabels" (dict "root" . "component" "db") | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "scd-reporting.selectorLabels" (dict "root" . "component" "db") | nindent 8 }}
    spec:
      containers:
        - name: db
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.db.name | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.db.user | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: POSTGRES_PASSWORD
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U {{ .Values.db.user }}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 10
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U {{ .Values.db.user }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 10
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
      restartPolicy: Always
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pgdata
