apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pgdata
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scd-reporting.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.pgdata.size }}
