apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scd-reporting.labels" . | nindent 4 }}
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ .Values.django.secretKey | quote }}
  SCD_INITIAL_ADMIN_PASSWORD: {{ .Values.django.initialAdminPassword | quote }}
  ANTHROPIC_API_KEY: {{ .Values.anthropic.apiKey | quote }}
  EMAIL_HOST_PASSWORD: {{ .Values.email.password | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.google.clientSecret | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.oidc.clientSecret | quote }}
  POSTGRES_PASSWORD: {{ .Values.db.password | quote }}
