apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-staticfiles
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scd-reporting.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.pvc.staticfiles.accessMode }}
  resources:
    requests:
      storage: {{ .Values.pvc.staticfiles.size }}
