apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scd-reporting-simple.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
  selector:
    {{- include "scd-reporting-simple.selectorLabels" . | nindent 4 }}
