# Generated by Django 5.2.14 on 2026-05-05 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taxonomy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "period_kind",
                    models.CharField(
                        choices=[
                            ("week", "Week"),
                            ("fortnight", "2 Weeks"),
                            ("month", "Month"),
                            ("custom", "Custom"),
                        ],
                        default="week",
                        max_length=12,
                    ),
                ),
                ("period_start", models.DateField(db_index=True)),
                ("period_end", models.DateField(db_index=True)),
                ("is_private", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_items",
                        to="taxonomy.category",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_items",
                        to="taxonomy.project",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="taxonomy.tag")),
            ],
            options={
                "ordering": ["-period_end", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["author", "-period_end"],
                        name="entries_wor_author__183dc0_idx",
                    ),
                    models.Index(
                        fields=["project", "-period_end"],
                        name="entries_wor_project_814625_idx",
                    ),
                    models.Index(
                        fields=["category", "-period_end"],
                        name="entries_wor_categor_3c98a4_idx",
                    ),
                    models.Index(
                        fields=["period_start", "period_end"],
                        name="entries_wor_period__ff0ab4_idx",
                    ),
                    models.Index(
                        fields=["is_private", "-period_end"],
                        name="entries_wor_is_priv_a0ab5a_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("period_end__gte", models.F("period_start"))
                        ),
                        name="entries_workitem_end_gte_start",
                    )
                ],
            },
        ),
    ]
