# Generated by Django 5.2.14 on 2026-05-06 19:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0001_initial"),
        ("taxonomy", "0002_workgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="workitem",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_items",
                to="taxonomy.workgroup",
            ),
        ),
        migrations.AddField(
            model_name="workitem",
            name="highlight_stars",
            field=models.PositiveSmallIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(5)]
            ),
        ),
        migrations.AddField(
            model_name="workitem",
            name="is_critical",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="workitem",
            name="is_highlight",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
