# Generated by Django 5.2.14 on 2026-05-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0002_workitem_group_workitem_highlight_stars_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workitem",
            name="period_kind",
            field=models.CharField(
                choices=[
                    ("today", "Today"),
                    ("week", "Week"),
                    ("fortnight", "2 Weeks"),
                    ("month", "Month"),
                    ("custom", "Custom"),
                ],
                default="week",
                max_length=12,
            ),
        ),
    ]
