# Generated by Django 5.2.14 on 2026-05-19 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0003_add_today_period_kind"),
        ("taxonomy", "0003_labpriority"),
    ]

    operations = [
        migrations.AddField(
            model_name="workitem",
            name="lab_priority",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_items",
                to="taxonomy.labpriority",
            ),
        ),
    ]
