# Generated by Django 5.2.14 on 2026-05-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0004_add_lab_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="workitem",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
