# Generated by Django 5.2.14 on 2026-06-25 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0007_add_entry_template"),
        ("taxonomy", "0004_entrytype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workitem",
            name="entry_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_items",
                to="taxonomy.entrytype",
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["entry_type", "-period_end"],
                name="entries_wor_entry_t_d54d2e_idx",
            ),
        ),
    ]
