# Generated by Django 5.2.14 on 2026-06-25 17:36
#
# Converts WorkItem.project / category / lab_priority (single FKs) to
# many-to-many relations (projects / categories / lab_priorities). The new
# M2M fields are added first, existing single values are copied across, and
# only then are the old FK columns removed — so no data is lost.

from django.db import migrations, models


def copy_fk_to_m2m(apps, schema_editor):
    WorkItem = apps.get_model("entries", "WorkItem")
    for item in WorkItem.objects.all():
        if item.project_id:
            item.projects.add(item.project_id)
        if item.category_id:
            item.categories.add(item.category_id)
        if item.lab_priority_id:
            item.lab_priorities.add(item.lab_priority_id)


def copy_m2m_to_fk(apps, schema_editor):
    # Reverse: collapse each M2M back to a single value (first by sort order).
    WorkItem = apps.get_model("entries", "WorkItem")
    for item in WorkItem.objects.all():
        project = item.projects.first()
        category = item.categories.first()
        lab_priority = item.lab_priorities.first()
        item.project = project
        item.category = category
        item.lab_priority = lab_priority
        item.save(update_fields=["project", "category", "lab_priority"])


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0008_workitem_entry_type_and_more"),
        ("taxonomy", "0003_labpriority"),
    ]

    operations = [
        migrations.AddField(
            model_name="workitem",
            name="categories",
            field=models.ManyToManyField(
                related_name="work_items", to="taxonomy.category"
            ),
        ),
        migrations.AddField(
            model_name="workitem",
            name="lab_priorities",
            field=models.ManyToManyField(
                blank=True, related_name="work_items", to="taxonomy.labpriority"
            ),
        ),
        migrations.AddField(
            model_name="workitem",
            name="projects",
            field=models.ManyToManyField(
                related_name="work_items", to="taxonomy.project"
            ),
        ),
        migrations.RunPython(copy_fk_to_m2m, copy_m2m_to_fk),
        migrations.RemoveIndex(
            model_name="workitem",
            name="entries_wor_project_814625_idx",
        ),
        migrations.RemoveIndex(
            model_name="workitem",
            name="entries_wor_categor_3c98a4_idx",
        ),
        migrations.RemoveField(
            model_name="workitem",
            name="category",
        ),
        migrations.RemoveField(
            model_name="workitem",
            name="lab_priority",
        ),
        migrations.RemoveField(
            model_name="workitem",
            name="project",
        ),
    ]
