# Generated by Django 5.2.14 on 2026-06-11 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_add_user_to_aipromptconfig"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NamedPromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "system_prompt",
                    models.TextField(
                        default="You are an analyst writing structured effort-reporting summaries for a scientific computing department. Your summaries are factual, professional, and well-organised. Use Markdown headings and bullet points. Do not invent information beyond what is provided."
                    ),
                ),
                (
                    "user_template",
                    models.TextField(
                        default="Below is a set of effort entries from the SCD Reporting system.\nPlease write a concise narrative summary that includes:\n\n1. **Overview** – date range covered, total entries, and authors involved.\n2. **Key Themes** – the main types of work and projects represented.\n3. **Notable Work** – standout contributions, especially any marked CRITICAL or HIGHLIGHT.\n4. **Summary Table** – a compact Markdown table with columns: Author | Project | Category | Period | Title.\n\n---\n{entries}\n"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Named Prompt Template",
                "ordering": ["name"],
                "unique_together": {("user", "name")},
            },
        ),
    ]
